# Generated by Django 4.2.8 on 2023-12-08 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPublic', models.BooleanField(db_column='is_public', default=False)),
                ('password', models.BinaryField(null=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='admins_chats', to=settings.AUTH_USER_MODEL)),
                ('banneds', models.ManyToManyField(blank=True, related_name='banned_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(db_column='content', max_length=500)),
                ('dateTime', models.DateTimeField(db_column='date_time')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong_chat.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(through='pong_chat.Message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='muteds',
            field=models.ManyToManyField(blank=True, related_name='muteds_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='usersChats',
            field=models.ManyToManyField(blank=True, related_name='users_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
