# Generated by Django 4.2.8 on 2023-12-11 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pong_chat', '0002_alter_chat_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='usersChats',
            field=models.ManyToManyField(blank=True, db_column='users_chats', related_name='users_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
