# Generated by Django 4.2.8 on 2024-01-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
