# Generated by Django 4.2.8 on 2024-03-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tournament_alias',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
