# Generated by Django 4.2.8 on 2023-12-12 18:25

from django.db import migrations
import srcs_user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', srcs_user.managers.IntraUserOAuth2Manager()),
            ],
        ),
    ]
