# Generated by Django 4.2.8 on 2024-01-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_user', '0002_remove_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id42',
            new_name='id_42',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is2fActive',
            new_name='is_2f_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='token2F',
            new_name='token_2F',
        ),
    ]
