# Generated by Django 4.2.8 on 2024-02-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_user', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_opened_chat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
