# Generated by Django 4.2.8 on 2024-02-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_user', '0005_user_last_opened_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_opened_chat',
        ),
    ]
