# Generated by Django 4.2.8 on 2024-03-29 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import srcs_tournament.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('srcs_game', '0003_game_is_finish_game_tournament_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('open_to_subscription', models.BooleanField(default=True)),
                ('register_date', models.DateTimeField(default=srcs_tournament.models.get_current_datetime)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('games', models.ManyToManyField(blank=True, db_column='games', related_name='games', to='srcs_game.game')),
                ('users', models.ManyToManyField(blank=True, db_column='users', related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
