# Generated by Django 4.2.8 on 2024-03-25 21:48

from django.db import migrations, models
import srcs_tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='register_date',
            field=models.DateTimeField(default=srcs_tournament.models.get_current_datetime),
        ),
    ]
