# Generated by Django 4.2.8 on 2024-02-29 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srcs_game', '0002_initial'),
        ('srcs_tournament', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='game',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='user',
        ),
        migrations.AddField(
            model_name='tournament',
            name='games',
            field=models.ManyToManyField(blank=True, db_column='games', related_name='games', to='srcs_game.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='open_to_subscription',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='users',
            field=models.ManyToManyField(blank=True, db_column='users', related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='tournament',
            table=None,
        ),
    ]
