# Generated by Django 4.2.8 on 2023-12-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='loses',
            new_name='loss',
        ),
    ]
