# Generated by Django 4.2.8 on 2023-12-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_users', '0003_rename_loses_user_loss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='expGame',
            new_name='mmr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blockedUsers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friendships',
        ),
        migrations.RemoveField(
            model_name='user',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wins',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
