# Generated by Django 4.2.8 on 2024-01-30 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srcs_message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
