# Generated by Django 4.2.8 on 2024-03-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_message', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(db_column='content'),
        ),
    ]
