# Generated by Django 4.2.8 on 2024-02-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_message', '0002_message_last_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='last_user',
        ),
    ]
