# Generated by Django 4.2.8 on 2024-02-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
