# Generated by Django 4.2.8 on 2024-02-21 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srcs_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='users_on_chat',
            field=models.ManyToManyField(blank=True, db_column='users_chats', related_name='users_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
