# Generated by Django 4.2.8 on 2023-12-29 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('srcs_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='users_on_chat',
            field=models.ManyToManyField(blank=True, db_column='users_chats', related_name='users_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
