# Generated by Django 4.2.8 on 2023-12-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_chat', '0002_remove_chat_admins_remove_chat_banneds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
