# Generated by Django 4.2.8 on 2024-01-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftPlayerScore', models.IntegerField(db_column='left_player_score')),
                ('rightPlayerScore', models.IntegerField(db_column='right_player_score')),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
