# Generated by Django 4.2.8 on 2024-01-27 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('srcs_game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='leftPlayer',
            field=models.ForeignKey(db_column='left_player', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_left_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='rightPlayer',
            field=models.ForeignKey(db_column='right_player', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_right_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
