# Generated by Django 4.2.8 on 2023-12-26 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srcs_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftPlayerScore', models.IntegerField(db_column='left_player_score')),
                ('rightPlayerScore', models.IntegerField(db_column='right_player_score')),
                ('leftPlayer', models.ForeignKey(db_column='left_player', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_left_player', to=settings.AUTH_USER_MODEL)),
                ('rightPlayer', models.ForeignKey(db_column='right_player', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_right_player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
