# Generated by Django 4.2.8 on 2024-03-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srcs_game', '0004_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
    ]
