# Generated by Django 4.2.8 on 2023-12-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_42', models.IntegerField(unique=True)),
                ('user_name', models.CharField(db_column='user_name', max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('password', models.BinaryField()),
                ('token_2f', models.CharField(blank=True, max_length=255)),
                ('is_2f_active', models.BooleanField(db_column='is_2f_active', default=False)),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('exp_game', models.FloatField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
