from static.game.scripts.Vector2 import Vector2

CANVAS_WIDTH = 800
CANVAS_HEIGHT = 640
OFFSET = 10
HALF_PADDLE_HEIGHT = 64
CENTER_OF_SCREEN = Vector2(CANVAS_WIDTH / 2, CANVAS_HEIGHT / 2)
LEFT_PADDLE_START_POSITION = (0 + OFFSET, 360)
RIGHT_PADDLE_START_POSITION = (CANVAS_WIDTH - OFFSET, 360)

PLAYER_LEFT = 0
PLAYER_RIGHT = 1
