CANVAS_WIDTH = 800
CANVAS_HEIGHT = 640
OFFSET = 10
CENTER_OF_SCREEN = (CANVAS_WIDTH / 2, CANVAS_HEIGHT / 2)
LEFT_PADDLE_START_POSITION = (0 + OFFSET, 360)
RIGHT_PADDLE_START_POSITION = (CANVAS_WIDTH - OFFSET, 360)

PLAYER_LEFT = 1
PLAYER_RIGHT = 2
