# Generated by Django 4.2.8 on 2023-12-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
