# Generated by Django 4.2.8 on 2023-12-11 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_users', '0003_user_blocked_users_user_followers_user_friendships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, db_column='blocked_users', related_name='blocking_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='blocked_users',
            new_name='blockedUsers',
        ),
    ]
